### ISSUE TITLE
Starting app for the first time

### ISSUE THREAD

**Issue by danielcsullog** [balazskosa/MakeItEasy#4]
When the user starts the app for first time or currently there is no user registered in the app, (maybe he/she deleted his user data) we have to decide what will happen. I think it is more user friendly when the "unregistered" app starts with profile creating, instead of confusing the user with default values, and forcing him/her to search where they can modify their data.
This is just my opinion, I'm open to anything.

**Comment by balazskosa** [comment]
Now the app starts with the default user's data or with the last saved user's data.
